async-config:
  - topic: employee-creation
    type: EmployeeCreatedNotification
    published: true
    consumed: false
  - topic: request-employeeCount
    type: RequestEmployeeCountNotification
    published: true
    consumed: false
  - topic: employee-count
    type: EmployeeCountNotification
    published: true
    consumed: false